// Server-side data access for the dashboard. Every page is a server component
// that calls these helpers, which fetch from the ingest REST API. Reads are
// uncached so the live runs view actually reflects what just happened.
//
// The base URL comes from config. A request that fails (the ingest service is
// down, say) throws, and pages catch it to show an empty or error state rather
// than crashing the whole dashboard.

import type { Agent, Run, Span, RunRollup } from "@overseer/schema";
import type { RunListItem, TrendBucket } from "./types";
import { computeTrends } from "./trends";
import { isReadOnly } from "./mode";
import demoSnapshot from "./demo-snapshot.json";

export function apiBaseUrl(): string {
  return process.env.OVERSEER_API_BASE_URL ?? "http://127.0.0.1:4318";
}

// Read-only (demo) mode serves the dashboard from a bundled synthetic snapshot:
// no ingest endpoint, no keys, no database. The snapshot is generated by the
// `overseer seed-demo` CLI.

// Typed view of the bundled snapshot. The JSON shape matches the API responses.
const snapshot = demoSnapshot as unknown as {
  generatedAtMs: number;
  agents: Agent[];
  runs: RunListItem[];
  details: Record<string, { run: Run; rollup: RunRollup | null; spans: Span[] }>;
};

// Translate a live time filter onto the snapshot's time base. Pages compute
// sinceMs against the real clock, but the demo data ends at generatedAtMs and
// only ages from there. Keeping the requested window length and anchoring it to
// the snapshot's end means "last 24h" shows the last day of demo data instead
// of nothing (or everything), no matter when the demo is viewed.
function snapshotSinceMs(sinceMs: number | undefined): number | undefined {
  if (sinceMs === undefined) return undefined;
  const windowMs = Date.now() - sinceMs;
  return snapshot.generatedAtMs - windowMs;
}

// The "now" that relative times should be formatted against. In demo mode that
// is the snapshot's generation time, so runs read "28m ago" forever instead of
// aging into "3mo ago" while the time filters still claim to show the last 24
// hours. Live mode uses the real clock.
export function dataNowMs(): number {
  return isReadOnly() ? snapshot.generatedAtMs : Date.now();
}

async function get<T>(path: string): Promise<T> {
  // The timeout keeps a stalled ingest service from hanging page renders
  // indefinitely; a refused connection already fails fast on its own.
  const res = await fetch(`${apiBaseUrl()}${path}`, {
    cache: "no-store",
    signal: AbortSignal.timeout(5000),
  });
  if (!res.ok) {
    throw new Error(`ingest API ${path} responded ${res.status}`);
  }
  return (await res.json()) as T;
}

function query(params: Record<string, string | number | undefined>): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined) search.set(key, String(value));
  }
  const s = search.toString();
  return s ? `?${s}` : "";
}

export async function fetchAgents(): Promise<Agent[]> {
  if (isReadOnly()) return snapshot.agents;
  const { agents } = await get<{ agents: Agent[] }>("/api/agents");
  return agents;
}

export async function fetchRuns(params: { agent?: string; sinceMs?: number; limit?: number } = {}): Promise<
  RunListItem[]
> {
  if (isReadOnly()) {
    let runs = snapshot.runs;
    if (params.agent) runs = runs.filter((r) => r.agent === params.agent);
    const since = snapshotSinceMs(params.sinceMs);
    if (since !== undefined) runs = runs.filter((r) => r.startMs >= since);
    return params.limit ? runs.slice(0, params.limit) : runs;
  }
  const { runs } = await get<{ runs: RunListItem[] }>(
    `/api/runs${query({ agent: params.agent, sinceMs: params.sinceMs, limit: params.limit })}`,
  );
  return runs;
}

export interface RunDetail {
  run: Run;
  rollup: RunRollup | null;
  spans: Span[];
}

export async function fetchRun(id: string): Promise<RunDetail | null> {
  // hasOwn, not a bare index: the id comes from the URL, and a plain lookup
  // would resolve names like "constructor" through the prototype chain and
  // hand the page a function instead of a run.
  if (isReadOnly()) return Object.hasOwn(snapshot.details, id) ? snapshot.details[id]! : null;
  try {
    return await get<RunDetail>(`/api/runs/${encodeURIComponent(id)}`);
  } catch {
    // A 404 (or any read failure) surfaces as "not found" to the page.
    return null;
  }
}

export async function fetchTrends(
  params: { agent?: string; sinceMs?: number; bucketMs?: number } = {},
): Promise<TrendBucket[]> {
  if (isReadOnly()) {
    let runs = params.agent ? snapshot.runs.filter((r) => r.agent === params.agent) : snapshot.runs;
    const since = snapshotSinceMs(params.sinceMs);
    if (since !== undefined) runs = runs.filter((r) => r.startMs >= since);
    return computeTrends(runs, params.bucketMs ?? 6 * 60 * 60 * 1000);
  }
  const { buckets } = await get<{ buckets: TrendBucket[] }>(
    `/api/trends${query({ agent: params.agent, sinceMs: params.sinceMs, bucketMs: params.bucketMs })}`,
  );
  return buckets;
}
