// Server-side data access for the dashboard. Every page is a server component
// that calls these helpers, which fetch from the ingest REST API. Reads are
// uncached so the live runs view actually reflects what just happened.
//
// The base URL comes from config. A request that fails (the ingest service is
// down, say) throws, and pages catch it to show an empty or error state rather
// than crashing the whole dashboard.

import type { Agent, Run, Span, RunRollup } from "@overseer/schema";
import type { RunListItem, TrendBucket } from "./types";
import { computeTrends } from "./trends";
import { isReadOnly } from "./mode";
import demoSnapshot from "./demo-snapshot.json";

export function apiBaseUrl(): string {
  return process.env.OVERSEER_API_BASE_URL ?? "http://127.0.0.1:4318";
}

// Read-only (demo) mode serves the dashboard from a bundled synthetic snapshot:
// no ingest endpoint, no keys, no database. The snapshot is generated by the
// `overseer seed-demo` CLI. Time-range lower bounds are ignored in this mode so
// the full demo dataset is always visible regardless of when it is viewed.

// Typed view of the bundled snapshot. The JSON shape matches the API responses.
const snapshot = demoSnapshot as unknown as {
  agents: Agent[];
  runs: RunListItem[];
  details: Record<string, { run: Run; rollup: RunRollup | null; spans: Span[] }>;
};

async function get<T>(path: string): Promise<T> {
  const res = await fetch(`${apiBaseUrl()}${path}`, { cache: "no-store" });
  if (!res.ok) {
    throw new Error(`ingest API ${path} responded ${res.status}`);
  }
  return (await res.json()) as T;
}

function query(params: Record<string, string | number | undefined>): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined) search.set(key, String(value));
  }
  const s = search.toString();
  return s ? `?${s}` : "";
}

export async function fetchAgents(): Promise<Agent[]> {
  if (isReadOnly()) return snapshot.agents;
  const { agents } = await get<{ agents: Agent[] }>("/api/agents");
  return agents;
}

export async function fetchRuns(params: { agent?: string; sinceMs?: number; limit?: number } = {}): Promise<
  RunListItem[]
> {
  if (isReadOnly()) {
    let runs = snapshot.runs;
    if (params.agent) runs = runs.filter((r) => r.agent === params.agent);
    return params.limit ? runs.slice(0, params.limit) : runs;
  }
  const { runs } = await get<{ runs: RunListItem[] }>(
    `/api/runs${query({ agent: params.agent, sinceMs: params.sinceMs, limit: params.limit })}`,
  );
  return runs;
}

export interface RunDetail {
  run: Run;
  rollup: RunRollup | null;
  spans: Span[];
}

export async function fetchRun(id: string): Promise<RunDetail | null> {
  if (isReadOnly()) return snapshot.details[id] ?? null;
  try {
    return await get<RunDetail>(`/api/runs/${encodeURIComponent(id)}`);
  } catch {
    // A 404 (or any read failure) surfaces as "not found" to the page.
    return null;
  }
}

export async function fetchTrends(
  params: { agent?: string; sinceMs?: number; bucketMs?: number } = {},
): Promise<TrendBucket[]> {
  if (isReadOnly()) {
    const runs = params.agent ? snapshot.runs.filter((r) => r.agent === params.agent) : snapshot.runs;
    return computeTrends(runs, params.bucketMs ?? 6 * 60 * 60 * 1000);
  }
  const { buckets } = await get<{ buckets: TrendBucket[] }>(
    `/api/trends${query({ agent: params.agent, sinceMs: params.sinceMs, bucketMs: params.bucketMs })}`,
  );
  return buckets;
}
